### PR TITLE
Minor update of FRENCH translation for Ajax Shoutbox extension

### PR DESCRIPTION
**Pull request by Galixte**
Minor update of FRENCH translation for permissions_ajax_shoutbox.php file

### CODE REVIEW

**Comment by paul999** [comment]
Permission texts should not end with a full stop.

**Comment by Galixte** [comment]
Ok sorry i have a french language pack with a lot of fool stops in permissions language keys, that was a bad habit.

I will ask to remove them.

**Comment by Galixte** [comment]
I come back to you, i have returned this information to the translator team of my language.

They asked to me where is the information from phpBB.com about this fact (no "full stop" at the end of the permission text) ?

**Comment by Galixte** [comment]
Hi,

can you give me an answer?

**Comment by Galixte** [comment]
Hi @paul999,

can i have an answer ?

**Comment by paul999** [comment]
Like I said, phpBB core doesn't use full stops, so neither should you.

**Comment by Galixte** [comment]
Hi,

i saw that in english language, but in french language we have a stop at the end of each sentence. 

Why you don't accept different rules according to the others languages ?

**Comment by ghost** [comment]
Sorry, but it's not about to accept a language rule. In the English punctuation, the full stop is also the punctuation mark placed at the end of a sentence, exactly like in French, there is no difference in that, this rule is the same in all latin and germanic languages.

However, we're talking here of a interface component, used in softwares, websites (and even paper books!). See all your software in French, you'll see a ton of sentences without the full stop.

In general, even in French, we do not use a full stop at the end of every sentence. See the index page of http://www.academie-francaise.fr/ (The French Language Academy, and they are not newbies to the French language): "Poser une question de langue sur un point précis de français", "Consulter le dictionnaire grâce à la collaboration de l’ATILF (CNRS-Université de Lorraine)", etc. Or http://www.gouvernement.fr/ (The French Government website): "Abonnez-vous à la lettre d'information". Correct me if I'm wrong, but there are sentences, with all the parts and structures of it. Just, like you see, there are no full stops. It's the exact same thing in English. And I don't even speak of list (even list of sentences, which generally do not have a full stop at the end).

It's an UI choice, and that's commonly like that everywhere since forever. So, it's nice to debate concerning a language difference, but this do not apply here. The French language adapts, as all the world's languages, to the context and the interface. So, I do not see what is wrong to not add full stops at the end of a list of permissions, even is they are sentences.

Just my two cents.

**Pull request closed without merging**
