### PR TITLE
Update acp_ajax_shoutbox.php & ajax_shoutbox.php

### PR DESCRIPTION
**Pull request by alhitary**

### CODE REVIEW

**Comment by paul999** [comment]
Please rebase your PR.

**Comment by alhitary** [comment]
Hi brother,
What rebase ?
I don't understand
Plz clarify

**Comment by paul999** [comment]
Sorry, I am not your brother.

Your branch is out of date with the master branch, so I am unable to merge your changes. You will need to rebase your branch, after which I can merge it.

**Comment by alhitary** [comment]
ha ha ha 
Sorry, we used to talk so in our traditions and call other brothers 
I didn't know it may get someone angry
Sorry

See plz now
I wish it work and could to rebase
https://github.com/paul999/ajax-shoutbox-ext/pull/70

**Pull request closed without merging**
