### PR TITLE
Arabic Translation Ajax-Shoutbox

### PR DESCRIPTION
**Pull request by alhitary**

### CODE REVIEW

**Comment by paul999** [comment]
There will be some more language changes in the coming weeks. Once you update your PR with all those changes I will merge it.

**Comment by alhitary** [comment]
Dear,
I updated the files

**Comment by paul999** [comment]
Hi,
Can you update your translation with the latest changes? There are no planned language changes from now on for BETA 2.

**Comment by alhitary** [comment]
inshaAllah ( God willing ) 2moro i'll update them.
Thanks

**Comment by paul999** [comment]
That's fine. Thanks a lot!

**Comment by alhitary** [comment]
Dear Brother,
I updated the files.
Thanks

**Comment by paul999** [comment]
https://travis-ci.org/paul999/ajax-shoutbox-ext/jobs/47706017#L681 <== can you fix those issues please?

**Pull request closed without merging**
